### ISSUE TITLE
Cannot Duplicate Items with Mongo $Commands

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimiPlugin-asset#2]
Trying to duplicate an object with this in the search field: 
{"assetType":"computer","fields.spiderStartTime":0,"lastSeen.inga.lastUpdate":{"$gt":"%%sum(now(),-90000)%%"}}

When JIMI tries to duplicate the object he runs into this issue:
![image](https://user-images.githubusercontent.com/14958920/97469921-d6f55080-193e-11eb-979b-298acb3caa0e.png)

**Comment by ghost** [comment]
Fixed in latest release of jimi 2.1
